from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Image, PageBreak, Preformatted, Table, TableStyle
import os

OUTPUT = "phase2/Phase2_Insight_Report.pdf"

doc = SimpleDocTemplate(
    OUTPUT,
    pagesize=A4,
    rightMargin=40,
    leftMargin=40,
    topMargin=40,
    bottomMargin=40
)

styles = getSampleStyleSheet()

title = ParagraphStyle(
    "TitleCustom",
    parent=styles["Title"],
    fontSize=22,
    leading=27,
    spaceAfter=15
)

heading = ParagraphStyle(
    "HeadingCustom",
    parent=styles["Heading2"],
    fontSize=15,
    leading=19,
    spaceBefore=12,
    spaceAfter=8
)

body = ParagraphStyle(
    "BodyCustom",
    parent=styles["BodyText"],
    fontSize=9.5,
    leading=14,
    spaceAfter=7
)

code_style = ParagraphStyle(
    "CodeCustom",
    fontName="Courier",
    fontSize=6.8,
    leading=9
)

story = []

print("PDF script started...")

code_style = ParagraphStyle(
    "CodeCustom",
    fontName="Courier",
    fontSize=6.8,
    leading=9
)

story = []

print("PDF script started...")

story.append(Spacer(1, 35))
story.append(Paragraph("DATA VORTEX — PHASE 2", title))
story.append(Paragraph("Social Engine Analytical Core", heading))
story.append(Spacer(1, 10))
story.append(Paragraph(
    "<b>Phase 2 Insight Report</b><br/>"
    "Analytical SQL, output evidence, logic explanation and insights",
    body
))
story.append(Spacer(1, 20))
story.append(Paragraph(
    "Database: DuckDB<br/>"
    "Dataset: Social Engine cleaned dataset<br/>"
    "Analysis period: May 2024 – April 2025",
    body
))
story.append(PageBreak())

story.append(Paragraph("1. Schema Design", heading))
story.append(Paragraph(
    "The cleaned Social Engine CSV files were converted into two analytical SQL tables: "
    "<b>users</b> and <b>posts</b>. DuckDB was used as the SQL engine.",
    body
))

schema_data = [
    ["Table", "Rows", "Purpose"],
    ["users", "1,500", "User-level profile and account information"],
    ["posts", "8,712", "Cleaned social-media posts and engagement metrics"]
]

table = Table(schema_data, colWidths=[1.2*inch, 1.0*inch, 4.2*inch])
table.setStyle(TableStyle([
    ("BACKGROUND", (0,0), (-1,0), colors.lightgrey),
    ("GRID", (0,0), (-1,-1), 0.5, colors.grey),
    ("FONTNAME", (0,0), (-1,0), "Helvetica-Bold"),
    ("FONTSIZE", (0,0), (-1,-1), 8),
    ("VALIGN", (0,0), (-1,-1), "MIDDLE"),
    ("TOPPADDING", (0,0), (-1,-1), 6),
    ("BOTTOMPADDING", (0,0), (-1,-1), 6),
]))
story.append(table)

story.append(Spacer(1, 10))
story.append(Paragraph(
    "<b>Relationship:</b> users.user_id → posts.user_id. "
    "One user can create multiple posts.",
    body
))

story.append(Paragraph(
    "<b>Key fields:</b> post_id, user_id, platform, timestamp, likes, "
    "shares, comments and total_engagement.",
    body
))

story.append(PageBreak())

story.append(Paragraph("2. SQL Queries", heading))

sql_text = open("phase2/phase2_analysis.sql").read()
statements = [s.strip() for s in sql_text.split(";") if s.strip()]

challenge_names = [
    "Challenge 1 — Trend Detection",
    "Challenge 2 — Platform Engagement Analysis",
    "Challenge 3 — High-Engagement Detection",
    "Challenge 4 — Behavioural User Grouping",
    "Challenge 5 — Correlation Analysis"
]

for name, statement in zip(challenge_names, statements):
    story.append(Paragraph(name, heading))
    story.append(Preformatted(statement + ";", code_style))
    story.append(Spacer(1, 8))

story.append(PageBreak())

story.append(Paragraph("3. Output Screenshots", heading))
story.append(Paragraph(
    "All outputs below were generated by executing the SQL queries directly "
    "against the DuckDB database. No analytical result was manually hardcoded.",
    body
))

images = [
    ("Challenge 1 — Monthly Trend", "phase2/output_01_trend.png"),
    ("Challenge 2 — Platform Engagement", "phase2/output_02_platform.png"),
    ("Challenge 3 — Top 10 High-Engagement Posts", "phase2/output_03_high_engagement.png"),
    ("Challenge 4 — Behavioural User Grouping", "phase2/output_04_behavior.png"),
    ("Challenge 5 — Correlation Analysis", "phase2/output_05_correlation.png"),
]

for caption, path in images:
    story.append(Paragraph(caption, heading))
    if os.path.exists(path):
        img = Image(path)
        img._restrictSize(6.8*inch, 6.5*inch)
        story.append(img)
    story.append(PageBreak())


story.append(Paragraph("4. Logic Explanation", heading))

logic = [
    ("Challenge 1 — Trend Detection",
     "The query groups posts by year-month using STRFTIME. COUNT(*) measures "
     "monthly post volume, while AVG(total_engagement) measures average engagement."),

    ("Challenge 2 — Platform Engagement",
     "The query groups posts by platform and calculates post count, average "
     "engagement and median engagement for comparison."),

    ("Challenge 3 — High-Engagement Detection",
     "ROW_NUMBER() ranks posts separately within each platform by total engagement. "
     "Only the top 10 ranks are retained, so the result is dynamically generated."),

    ("Challenge 4 — Behavioural User Grouping",
     "A CTE calculates each user's post count and average engagement. CASE then "
     "classifies users as Power, Active or Casual users according to posting frequency."),

    ("Challenge 5 — Correlation Analysis",
     "DuckDB CORR() calculates Pearson correlation between likes, shares and comments. "
     "Values close to zero indicate little linear relationship.")
]

for name, explanation in logic:
    story.append(Paragraph(name, heading))
    story.append(Paragraph(explanation, body))

story.append(PageBreak())

story.append(Paragraph("5. Phase 2 Insight Report", heading))

insights = [
    "<b>Monthly activity:</b> May 2024 had the highest post volume with 761 posts, "
    "while February 2025 had the lowest with 667 posts.",

    "<b>Engagement trend:</b> Average engagement fluctuated rather than showing a "
    "consistent upward or downward trend. March 2025 recorded the highest monthly "
    "average engagement at 4,074.86.",

    "<b>Platform performance:</b> Instagram had the highest average engagement at "
    "4,038.52, while Facebook had the highest median engagement at 4,050.",

    "<b>High-engagement posts:</b> The window-function analysis identified the top "
    "10 posts within every platform. The highest individual engagement value was "
    "7,893 on Instagram.",

    "<b>User behaviour:</b> Active Users formed the largest group with 890 users. "
    "Power Users numbered 114 and had the highest average engagement among the groups.",

    "<b>Correlation:</b> Likes-shares correlation was 0.0014, likes-comments was "
    "0.0098, and shares-comments was 0.0223. All are very close to zero.",

    "<b>Anomaly screening:</b> The Phase 1 IQR audit found no total-engagement "
    "outliers. Therefore, the high-engagement analysis focuses on relative extremes "
    "within each platform rather than claiming they are statistical outliers."
]

for item in insights:
    story.append(Paragraph("• " + item, body))

story.append(PageBreak())

story.append(Paragraph("6. Methodology & Reproducibility", heading))
story.append(Paragraph(
    "All analytical challenges were executed using SQL against the DuckDB database. "
    "The outputs were generated directly from the dataset rather than manually entered.",
    body
))

def add_page_number(canvas, doc):
    canvas.saveState()
    canvas.setFont("Helvetica", 7)
    canvas.drawCentredString(A4[0] / 2, 20, f"DATA VORTEX — Phase 2 | Page {doc.page}")
    canvas.restoreState()

doc.build(story, onFirstPage=add_page_number, onLaterPages=add_page_number)
print(f"PDF created successfully: {OUTPUT}")
